config/routes.rb
StarOR::Application.routes.draw do
  resources :sessions, :only  => [:new, :create, :destroy]
  match 'login' => 'sessions#new'

  get "sessions/new"

  get "sessions/run"

  get "sessions/create"

  get "sessions/destroy"

  resources :administrator_menu, :only  => [:new, :create, :destroy]
  match 'Menu' => 'administrator_menu#new'

  get "administrator_menu/new"

  get "administrator_menu/run"

  get "administrator_menu/create"

  get "administrator_menu/destroy"

end

app/models/user_header_dto.rb
class UserHeaderDto
  attr_accessor :DegreeTitleId, :DegreeTitleCode, :UserId, :FirstName, :MiddleInitial, :LastName

    def initialize()

    end



end

app/controllers/administrator_menu_controller.rb
class AdministratorMenuController < ApplicationController
  def new

  end

  def create

  end

  def destroy

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end



  def create
    @session = params[:session]
    @userName = params[:session][:username]

    @password = params[:session][:password]

    require 'net/http'
    require 'uri'
    uri = URI.parse('http://mango.microbitinfo.com/StarOR/User/UserHeader')
    http = Net::HTTP.new(uri.host, uri.port)

    request = Net::HTTP::Get.new(uri.request_uri,{'Content_Type' => 'application/json'})
    request.basic_auth(@userName, @password)
    response, data= http.request request
    render :text => "#{data}"
    data = response.body
    result = JSON.parse(data)
    #result1 =  ActiveSupport::JSON.decode(data)
    if result.has_key? 'Error'
      raise "GetUserHeader service error!"
    end

    if (response.code == "200")
      userId = JSON.parse(data)['Data']['UserId']
      firstName =   JSON.parse(data)['Data']['FirstName']
      lastName =   JSON.parse(data)['Data']['LastName']
      facility =   JSON.parse(data)['Data']['Facility']['FacilityName']
      degreeTitle =  JSON.parse(data)['Data']['DegreeTitleLookup']['Code']
      status = JSON.parse(data)['Status']

      flash.now[:notice] = "Welcome " + degreeTitle + " " + firstName + " " + lastName

    else
      flash[:notice] = "Invalid User Name or Password. Try Again."
     # render :action => :new
    end



    a = @userName
  end

  def destroy
  end
end

app/helpers/administrator_menu_helper.rb
module AdministratorMenuHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/administrator_menu/new.html.erb
<h1>Administrative Menu</h1>
<p>Welcome to the StarOR administrative application! Please select function.</p>

<%= form_for(:administrator_menu, :url => administrator_menu_path) do |f| %>
    <div>
      <%=f.submit "Create New User" %>
    </div>

    <div>
      <%=f.submit "Create new Role" %>
    </div>
    <div>
      <%=f.submit "Create new Permission" %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StarOR</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>